#!/bin/bash

remote='petition.pecina.cz'

rsync -avhHzx \
      --exclude '.*' \
      --exclude '*.pyc' \
      --exclude '*.pyc' \
      --exclude '*~' \
      --exclude '/update' \
      --exclude '/collect/admin/' \
      --exclude '/aux/' \
      --exclude '*.po' \
      --exclude 'migrations/' \
      --exclude '__pycache__/' \
      --exclude '/venv*' \
      --exclude '/repo/udn/*' \
      --exclude 'test*' \
      --exclude 'fixtures/*_test*.json' \
      --exclude '/test/' \
      --exclude '/htmlcov/' \
      --exclude '#*' \
      --delete \
      ./ $remote:/var/www/django/legal/

ssh $remote 'touch /var/www/django/petition/petition/wsgi.py'
